/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.operaciones;
import modelo.bitacora;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane; //para mostrar cuadros de diálogo estándar, como mensajes de información.
import java.awt.Toolkit;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;

/**
 *
 * @author DELL
 */
public class frm_calculadora extends javax.swing.JFrame {
    private operaciones op;
    private char operador;
    private double num1;
    private boolean operacionEnCurso = false;
    
    public frm_calculadora() {
        op = new operaciones();
        initComponents();
        this.setLocationRelativeTo(null);
        this.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                handleKeyPress(e);
                Toolkit.getDefaultToolkit().beep(); // Emite un beep
            }
        });
        this.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                frm_calculadora.this.setFocusable(true);
                frm_calculadora.this.requestFocusInWindow();
            }
        });
        this.setFocusable(true);
        this.requestFocusInWindow();
    }
    
    
    // Método para manejar las teclas presionadas
    private void handleKeyPress(KeyEvent e) {
        int keyCode = e.getKeyCode();
        switch (keyCode) {
            case KeyEvent.VK_0: case KeyEvent.VK_NUMPAD0:
                btn_0ActionPerformed(null);
                break;
            case KeyEvent.VK_1: case KeyEvent.VK_NUMPAD1:
                btn_1ActionPerformed(null);
                break;
            case KeyEvent.VK_2: case KeyEvent.VK_NUMPAD2:
                btn_2ActionPerformed(null);
                break;
            case KeyEvent.VK_3: case KeyEvent.VK_NUMPAD3:
                btn_3ActionPerformed(null);
                break;
            case KeyEvent.VK_4: case KeyEvent.VK_NUMPAD4:
                btn_4ActionPerformed(null);
                break;
            case KeyEvent.VK_5: case KeyEvent.VK_NUMPAD5:
                btn_5ActionPerformed(null);
                break;
            case KeyEvent.VK_6: case KeyEvent.VK_NUMPAD6:
                btn_6ActionPerformed(null);
                break;
            case KeyEvent.VK_7: case KeyEvent.VK_NUMPAD7:
                btn_7ActionPerformed(null);
                break;
            case KeyEvent.VK_8: case KeyEvent.VK_NUMPAD8:
                btn_8ActionPerformed(null);
                break;
            case KeyEvent.VK_9: case KeyEvent.VK_NUMPAD9:
                btn_9ActionPerformed(null);
                break;
            case KeyEvent.VK_PLUS:
                btn_masActionPerformed(null);
                break;
            case KeyEvent.VK_MINUS:
                btn_menosActionPerformed(null);
                break;
            case KeyEvent.VK_MULTIPLY:
                btn_porActionPerformed(null);
                break;
            case KeyEvent.VK_DIVIDE:
                btn_divisionActionPerformed(null);
                break;
            case KeyEvent.VK_PERIOD:
                btn_puntoActionPerformed(null);
                break;
            case KeyEvent.VK_ENTER:
                btn_calcularActionPerformed(null);
                break;
            case KeyEvent.VK_BACK_SPACE:
                btn_backspaceActionPerformed(null);
                break;
            case KeyEvent.VK_ESCAPE:
                btn_escapeActionPerformed(null);
                break;
            default:
                break;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        pn_principal = new javax.swing.JPanel();
        lbl_pantalla = new javax.swing.JLabel();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_mas = new javax.swing.JButton();
        btn_menos = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_por = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        btn_calcular = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        mnB_principal = new javax.swing.JMenuBar();
        mn_opciones = new javax.swing.JMenu();
        mnI_nuevo = new javax.swing.JMenuItem();
        mnI_historial = new javax.swing.JMenuItem();
        mn_ayuda = new javax.swing.JMenu();
        mnI_Manual_Usuario = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_principal.setBackground(new java.awt.Color(153, 153, 153));

        lbl_pantalla.setBackground(new java.awt.Color(255, 255, 255));
        lbl_pantalla.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_pantalla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_pantalla.setOpaque(true);

        btn_1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_1.setText("1");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_mas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_mas.setText("+");
        btn_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masActionPerformed(evt);
            }
        });

        btn_menos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_menos.setText("-");
        btn_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menosActionPerformed(evt);
            }
        });

        btn_6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_por.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_por.setText("*");
        btn_por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_porActionPerformed(evt);
            }
        });

        btn_9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_division.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_division.setText("/");
        btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisionActionPerformed(evt);
            }
        });

        btn_calcular.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_calcular.setText("=");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        btn_punto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_punto.setText(".");
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });

        btn_0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_principalLayout = new javax.swing.GroupLayout(pn_principal);
        pn_principal.setLayout(pn_principalLayout);
        pn_principalLayout.setHorizontalGroup(
            pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_principalLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_principalLayout.createSequentialGroup()
                        .addComponent(lbl_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_principalLayout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pn_principalLayout.createSequentialGroup()
                                .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btn_por, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pn_principalLayout.createSequentialGroup()
                                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pn_principalLayout.createSequentialGroup()
                                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(btn_mas, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pn_principalLayout.createSequentialGroup()
                                .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btn_division, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61))))
        );
        pn_principalLayout.setVerticalGroup(
            pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_principalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbl_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_por, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_division, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        mn_opciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mn_opciones.setText("Opciones");

        mnI_nuevo.setText("Nuevo");
        mnI_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnI_nuevoActionPerformed(evt);
            }
        });
        mn_opciones.add(mnI_nuevo);

        mnI_historial.setText("Historial");
        mnI_historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnI_historialActionPerformed(evt);
            }
        });
        mn_opciones.add(mnI_historial);

        mnB_principal.add(mn_opciones);

        mn_ayuda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mn_ayuda.setText("Ayuda");

        mnI_Manual_Usuario.setText("Manual de Usuario");
        mnI_Manual_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnI_Manual_UsuarioActionPerformed(evt);
            }
        });
        mn_ayuda.add(mnI_Manual_Usuario);

        mnB_principal.add(mn_ayuda);

        setJMenuBar(mnB_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        Toolkit.getDefaultToolkit().beep(); // Emite un beep
        this.lbl_pantalla.setText(this.lbl_pantalla.getText() + "4");
        this.requestFocusInWindow();
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        Toolkit.getDefaultToolkit().beep(); // Emite un beep
        this.lbl_pantalla.setText(this.lbl_pantalla.getText() + "0");
        this.requestFocusInWindow();
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        Toolkit.getDefaultToolkit().beep(); // Emite un beep
        this.lbl_pantalla.setText(this.lbl_pantalla.getText() + "1");
        this.requestFocusInWindow();
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        Toolkit.getDefaultToolkit().beep(); // Emite un beep
        this.lbl_pantalla.setText(this.lbl_pantalla.getText() + "2");
        this.requestFocusInWindow();
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        Toolkit.getDefaultToolkit().beep(); // Emite un beep
        this.lbl_pantalla.setText(this.lbl_pantalla.getText() + "3");
        this.requestFocusInWindow();
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        Toolkit.getDefaultToolkit().beep(); // Emite un beep
        this.lbl_pantalla.setText(this.lbl_pantalla.getText() + "5");
        this.requestFocusInWindow();
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        Toolkit.getDefaultToolkit().beep(); // Emite un beep
        this.lbl_pantalla.setText(this.lbl_pantalla.getText() + "6");
        this.requestFocusInWindow();
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        Toolkit.getDefaultToolkit().beep(); // Emite un beep
        this.lbl_pantalla.setText(this.lbl_pantalla.getText() + "7");
        this.requestFocusInWindow();
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        Toolkit.getDefaultToolkit().beep(); // Emite un beep
        this.lbl_pantalla.setText(this.lbl_pantalla.getText() + "8");
        this.requestFocusInWindow();
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        Toolkit.getDefaultToolkit().beep(); // Emite un beep
        this.lbl_pantalla.setText(this.lbl_pantalla.getText() + "9");
        this.requestFocusInWindow();
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masActionPerformed
        Toolkit.getDefaultToolkit().beep(); // Emite un beep
        setOperador('+');
        this.requestFocusInWindow();
    }//GEN-LAST:event_btn_masActionPerformed

    private void btn_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menosActionPerformed
        Toolkit.getDefaultToolkit().beep(); // Emite un beep
        setOperador('-');
        this.requestFocusInWindow();
    }//GEN-LAST:event_btn_menosActionPerformed

    private void btn_porActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_porActionPerformed
        Toolkit.getDefaultToolkit().beep(); // Emite un beep
        setOperador('*');
        this.requestFocusInWindow();
    }//GEN-LAST:event_btn_porActionPerformed

    private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
        Toolkit.getDefaultToolkit().beep(); // Emite un beep
        setOperador('/');
        this.requestFocusInWindow();
    }//GEN-LAST:event_btn_divisionActionPerformed

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
       Toolkit.getDefaultToolkit().beep(); // Emite un beep
        String text = this.lbl_pantalla.getText();
        if (!text.contains(".")) {
            this.lbl_pantalla.setText(text + ".");
        }
        this.requestFocusInWindow();
    }//GEN-LAST:event_btn_puntoActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        Toolkit.getDefaultToolkit().beep(); // Emite un beep
        if (operacionEnCurso) {
            double num2;
            try {
                num2 = Double.parseDouble(this.lbl_pantalla.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Número inválido", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            op.setNum1(num1);
            op.setNum2(num2);
            op.setOperador(operador);
            op.calcular();
            this.lbl_pantalla.setText(String.valueOf(op.getResult()));
            operacionEnCurso = false;
        }
        this.requestFocusInWindow();                                           
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void mnI_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnI_historialActionPerformed
        frm_historial historial = new frm_historial();
        historial.setVisible(true);
    }//GEN-LAST:event_mnI_historialActionPerformed

    private void mnI_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnI_nuevoActionPerformed
        // Reiniciar la calculadora
        this.lbl_pantalla.setText("");
        this.num1 = 0;
        this.operador = '\0'; // Operador nulo
        this.operacionEnCurso = false;

        // Grabar la operación en el archivo de bitácora
        bitacora.escribirEnBitacora("Operación Nuevo");
    }//GEN-LAST:event_mnI_nuevoActionPerformed

    private void mnI_Manual_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnI_Manual_UsuarioActionPerformed
        manual_usuario manual = new manual_usuario();
        manual.setVisible(true);
    }//GEN-LAST:event_mnI_Manual_UsuarioActionPerformed
    
    private void setOperador(char operador) {
    try {
        num1 = Double.parseDouble(this.lbl_pantalla.getText());
        this.operador = operador;
        this.lbl_pantalla.setText("");
        operacionEnCurso = true;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Número inválido", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_mas;
    private javax.swing.JButton btn_menos;
    private javax.swing.JButton btn_por;
    private javax.swing.JButton btn_punto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_pantalla;
    private javax.swing.JMenuBar mnB_principal;
    private javax.swing.JMenuItem mnI_Manual_Usuario;
    private javax.swing.JMenuItem mnI_historial;
    private javax.swing.JMenuItem mnI_nuevo;
    private javax.swing.JMenu mn_ayuda;
    private javax.swing.JMenu mn_opciones;
    private javax.swing.JPanel pn_principal;
    // End of variables declaration//GEN-END:variables

    private void btn_backspaceActionPerformed(java.awt.event.ActionEvent evt) {
        String text = lbl_pantalla.getText();
        if (!text.isEmpty()) {
            lbl_pantalla.setText(text.substring(0, text.length() - 1));
        }
    }

    private void btn_escapeActionPerformed(java.awt.event.ActionEvent evt) {
        lbl_pantalla.setText("");
        operacionEnCurso = false;
    }
}
